# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MovieApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieApp
  pod "youtube-ios-player-helper", "~> 1.0.3"
  pod 'Alamofire', '~> 5.0'
  pod 'Kingfisher', '~> 5.0'
end
